services:
  mysql:
    image: mysql:8.0
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db-net

  snwa-backend:
    build: ./snwa-backend
    image: snwa-backend-server:v1
    expose:
      - 8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      APP_BASE_URL: http://localhost:70
      DEEPL_API_KEY: ${DEEPL_API_KEY}
      DEEPL_API_BASE_URL: ${DEEPL_API_BASE_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_STATIC: ${AWS_REGION_STATIC}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

    networks:
      - backend-net
      - db-net

  snwa-frontend:
    build: ./snwa-frontend
    image: snwa-frontend-server:v1
    depends_on:
      - snwa-backend
    networks:
      - frontend-net

  nginx:
    build: ./nginx
    image: snwa-nginx:v1
    ports:
      - 70:80
    depends_on:
      - snwa-backend
      - snwa-frontend
    networks:
      - backend-net
      - frontend-net

networks:
  backend-net:
  frontend-net:
  db-net:

volumes:
  mysql_data: