server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # 캐시 방지 헤더 추가
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    add_header Pragma "no-cache";
    add_header Expires "0";

    location / {
        try_files $uri /index.html;
        
        # 정적 파일 캐시 방지
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # JavaScript와 CSS 파일 캐시 방지
    location ~* \.(js|css)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }
}