import { useEffect, useState } from 'react';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Play, Trash2, StopCircle, RefreshCw, Plus } from 'lucide-react';
import { toast } from 'sonner';

type SourceName = 'ESPN' | 'SKY_SPORTS' | 'BBC';
type EspnLeague = 'NBA' | 'EPL' | 'LALIGA' | 'BUNDESLIGA' | 'SERIEA' | 'LIGUE1' | 'CHAMPIONS_LEAGUE' | 'MLB';

type CrawlingJob = {
    id: number;
    category?: { id: number; name: string };
    sourceName: SourceName;
    jobName: string;
    targetUrl: string;
    cronExpression: string;
    active: boolean;
    lastRunAt: string | null;
};

type CreateJobRequest = {
    sourceName: SourceName;
    jobName: string;
    targetUrl?: string;
    categoryId: number;
    cronExpression: string;
    league?: EspnLeague;
};

function getAuthHeader() {
    const token = sessionStorage.getItem('snwa_token');
    if (!token) return null;
    return { Authorization: `Bearer ${token}` };
}

export default function CrawlerJobs() {
    const [jobs, setJobs] = useState<CrawlingJob[]>([]);
    const [loading, setLoading] = useState(false);
    const [createOpen, setCreateOpen] = useState(false);
    
    // Form States
    const [formData, setFormData] = useState<CreateJobRequest>({
        sourceName: 'ESPN',
        jobName: '',
        targetUrl: '',
        categoryId: 1, // Default to 1
        cronExpression: '0 0 * * * *', // Default hourly
    });

    const fetchJobs = async () => {
        const auth = getAuthHeader();
        if (!auth) return;

        setLoading(true);
        try {
            const res = await fetch('/api/admin/crawler/jobs', { headers: { ...auth } });
            if (res.ok) {
                const data = await res.json();
                setJobs(data);
            }
        } catch (error) {
            toast.error("작업 목록을 불러오지 못했습니다.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchJobs();
    }, []);

    const handleCreateJob = async () => {
        const auth = getAuthHeader();
        if (!auth) return;

        try {
            // Validate inputs
            if (!formData.jobName.trim()) {
                toast.error("작업명을 입력해주세요.");
                return;
            }

            if ((formData.sourceName === 'ESPN' || formData.sourceName === 'SKY_SPORTS') && !formData.league) {
                toast.error("리그를 선택해주세요.");
                return;
            }

            if (formData.sourceName !== 'ESPN' && formData.sourceName !== 'SKY_SPORTS' && !formData.targetUrl) {
                toast.error("타겟 URL을 입력해주세요.");
                return;
            }

            // Construct payload based on source
            const payload: any = {
                sourceName: formData.sourceName,
                jobName: formData.jobName,
                categoryId: formData.categoryId,
                cronExpression: formData.cronExpression
            };

            if (formData.sourceName === 'ESPN' || formData.sourceName === 'SKY_SPORTS') {
                payload.league = formData.league;
                // targetUrl is intentionally excluded for ESPN and SKY_SPORTS as it's generated by backend
            } else {
                payload.targetUrl = formData.targetUrl;
            }

            const res = await fetch('/api/admin/crawler/jobs', {
                method: 'POST',
                headers: { 
                    ...auth,
                    'Content-Type': 'application/json' 
                },
                body: JSON.stringify(payload)
            });

            if (res.ok) {
                toast.success("새 작업이 생성되었습니다.");
                setCreateOpen(false);
                fetchJobs();
            } else {
                const text = await res.text();
                toast.error(`생성 실패: ${text}`);
            }
        } catch (e) {
            toast.error("오류가 발생했습니다.");
        }
    };

    const toggleActive = async (job: CrawlingJob) => {
        const auth = getAuthHeader();
        if (!auth) return;

        const nextState = !job.active;
        try {
            const res = await fetch(`/api/admin/crawler/jobs/${job.id}`, {
                method: 'PATCH',
                headers: { 
                    ...auth,
                    'Content-Type': 'application/json' 
                },
                body: JSON.stringify({ 
                    isActive: nextState,
                    cronExpression: job.cronExpression 
                })
            });

            if (res.ok) {
                toast.success(nextState ? "작업이 활성화되었습니다." : "작업이 정지되었습니다.");
                fetchJobs();
            } else {
                toast.error("상태 변경 실패");
            }
        } catch (e) {
            toast.error("오류가 발생했습니다.");
        }
    };

    const deleteJob = async (id: number) => {
        if (!confirm("정말 이 작업을 삭제하시겠습니까?")) return;
        const auth = getAuthHeader();
        if (!auth) return;

        try {
            const res = await fetch(`/api/admin/crawler/jobs/${id}`, {
                method: 'DELETE',
                headers: { ...auth }
            });

            if (res.ok) {
                toast.success("작업이 삭제되었습니다.");
                fetchJobs();
            } else {
                toast.error("삭제 실패");
            }
        } catch (e) {
            toast.error("오류가 발생했습니다.");
        }
    };

    const runJob = async (id: number) => {
        if (!confirm("지금 즉시 실행하시겠습니까?")) return;
        const auth = getAuthHeader();
        if (!auth) return;

        try {
            const res = await fetch(`/api/admin/crawler/jobs/${id}/run`, {
                method: 'POST',
                headers: { ...auth }
            });

            if (res.ok) {
                toast.success("실행 요청이 전송되었습니다.");
            } else {
                toast.error("실행 요청 실패");
            }
        } catch (e) {
            toast.error("오류가 발생했습니다.");
        }
    };

    return (
        <div className="space-y-4">
            <div className="flex justify-between items-center">
                <h3 className="text-lg font-medium">크롤링 작업 목록</h3>
                <Button onClick={() => setCreateOpen(true)}>
                    <Plus className="w-4 h-4 mr-2" />
                    새 작업 등록
                </Button>
                <Dialog open={createOpen} onOpenChange={setCreateOpen}>
                    <DialogContent className="sm:max-w-[425px] bg-white">
                        <DialogHeader>
                            <DialogTitle>새 크롤링 작업 등록</DialogTitle>
                            <DialogDescription>
                                새로운 뉴스 소스를 등록하여 주기적으로 수집합니다.
                            </DialogDescription>
                        </DialogHeader>
                        <div className="grid gap-4 py-4">
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="source" className="text-right">소스</Label>
                                <Select 
                                    value={formData.sourceName} 
                                    onValueChange={(v) => setFormData({...formData, sourceName: v as SourceName})}
                                >
                                    <SelectTrigger className="col-span-3">
                                        <SelectValue placeholder="소스 선택" />
                                    </SelectTrigger>
                                    <SelectContent className="bg-white">
                                        <SelectItem value="ESPN">ESPN</SelectItem>
                                        <SelectItem value="SKY_SPORTS">SKY_SPORTS</SelectItem>
                                        <SelectItem value="BBC">BBC</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            {(formData.sourceName === 'ESPN' || formData.sourceName === 'SKY_SPORTS') && (
                                <div className="grid grid-cols-4 items-center gap-4">
                                    <Label htmlFor="league" className="text-right">리그</Label>
                                    <Select 
                                        value={formData.league || ''} 
                                        onValueChange={(v) => setFormData({...formData, league: v as EspnLeague, jobName: v, targetUrl: ''})}
                                    >
                                        <SelectTrigger className="col-span-3">
                                            <SelectValue placeholder="리그 선택" />
                                        </SelectTrigger>
                                        <SelectContent className="bg-white">
                                            <SelectItem value="EPL">EPL (EPL (잉글랜드))</SelectItem>
                                            <SelectItem value="LALIGA">LALIGA (La Liga (스페인))</SelectItem>
                                            <SelectItem value="BUNDESLIGA">BUNDESLIGA (Bundesliga (독일))</SelectItem>
                                            <SelectItem value="SERIEA">SERIEA (Serie A (이탈리아))</SelectItem>
                                            <SelectItem value="LIGUE1">LIGUE1 (Ligue 1 (프랑스))</SelectItem>
                                            <SelectItem value="CHAMPIONS_LEAGUE">CHAMPIONS_LEAGUE (UEFA 챔피언스리그)</SelectItem>
                                            <SelectItem value="NBA">NBA</SelectItem>
                                            <SelectItem value="MLB">MLB</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                            )}

                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="name" className="text-right">작업명</Label>
                                <Input 
                                    id="name" 
                                    value={formData.jobName}
                                    onChange={(e) => setFormData({...formData, jobName: e.target.value})}
                                    className="col-span-3" 
                                    placeholder="예: EPL 주요 뉴스"
                                />
                            </div>
                            
                            {(formData.sourceName !== 'ESPN' && formData.sourceName !== 'SKY_SPORTS') && (
                                <div className="grid grid-cols-4 items-center gap-4">
                                    <Label htmlFor="url" className="text-right">URL</Label>
                                    <Input 
                                        id="url" 
                                        value={formData.targetUrl}
                                        onChange={(e) => setFormData({...formData, targetUrl: e.target.value})}
                                        className="col-span-3" 
                                        placeholder="수집 대상 URL"
                                    />
                                </div>
                            )}

                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="cron" className="text-right">Cron</Label>
                                <Input 
                                    id="cron" 
                                    value={formData.cronExpression}
                                    onChange={(e) => setFormData({...formData, cronExpression: e.target.value})}
                                    className="col-span-3" 
                                    placeholder="0 0 * * * *"
                                />
                            </div>
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="category" className="text-right">카테고리ID</Label>
                                <Input 
                                    id="category" 
                                    type="number"
                                    value={formData.categoryId}
                                    onChange={(e) => setFormData({...formData, categoryId: parseInt(e.target.value) || 1})}
                                    className="col-span-3" 
                                    placeholder="1"
                                />
                            </div>
                        </div>
                        <DialogFooter>
                            <Button type="button" onClick={handleCreateJob}>등록</Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </div>

            <div className="rounded-md border bg-white">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead className="w-[60px]">ID</TableHead>
                            <TableHead>소스</TableHead>
                            <TableHead>이름</TableHead>
                            <TableHead>URL / Cron</TableHead>
                            <TableHead>상태</TableHead>
                            <TableHead>마지막 실행</TableHead>
                            <TableHead className="text-right">관리</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                         {loading && jobs.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={7} className="text-center py-8">로딩 중...</TableCell>
                            </TableRow>
                        ) : jobs.length === 0 ? (
                            <TableRow>
                                <TableCell colSpan={7} className="text-center py-8">등록된 작업이 없습니다.</TableCell>
                            </TableRow>
                        ) : (
                            jobs.map((job) => (
                                <TableRow key={job.id}>
                                    <TableCell className="font-medium">{job.id}</TableCell>
                                    <TableCell>{job.sourceName}</TableCell>
                                    <TableCell className="font-medium">{job.jobName}</TableCell>
                                    <TableCell className="max-w-[250px]">
                                        <div className="truncate text-xs text-gray-500" title={job.targetUrl}>{job.targetUrl}</div>
                                        <div className="text-xs font-mono bg-gray-100 inline-block px-1 rounded mt-1">{job.cronExpression}</div>
                                    </TableCell>
                                    <TableCell>
                                        <Badge variant={job.active ? "default" : "secondary"} className={job.active ? "bg-green-600" : ""}>
                                            {job.active ? "Active" : "Stopped"}
                                        </Badge>
                                    </TableCell>
                                    <TableCell className="text-sm">
                                        {job.lastRunAt ? new Date(job.lastRunAt).toLocaleString('ko-KR') : '-'}
                                    </TableCell>
                                    <TableCell className="text-right">
                                        <div className="flex justify-end gap-2">
                                            <Button 
                                                variant="outline" 
                                                size="icon" 
                                                onClick={() => toggleActive(job)}
                                                title={job.active ? "일시정지" : "재개"}
                                            >
                                                {job.active ? <StopCircle className="h-4 w-4" /> : <Play className="h-4 w-4" />}
                                            </Button>
                                            <Button 
                                                variant="outline" 
                                                size="icon" 
                                                onClick={() => runJob(job.id)}
                                                title="즉시 실행"
                                            >
                                                <RefreshCw className="h-4 w-4" />
                                            </Button>
                                            <Button 
                                                variant="outline" 
                                                size="icon" 
                                                className="text-red-500 hover:text-red-600 hover:bg-red-50"
                                                onClick={() => deleteJob(job.id)}
                                                title="삭제"
                                            >
                                                <Trash2 className="h-4 w-4" />
                                            </Button>
                                        </div>
                                    </TableCell>
                                </TableRow>
                            ))
                        )}
                    </TableBody>
                </Table>
            </div>
        </div>
    );
}
