spring:
  application:
    name: snwa-backend

  datasource:
    url: jdbc:mysql://localhost:3306/snwa
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always # 항상 data.sql 실행 시도

  #S3 오류 해결시 삭제
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

#  # aws/s3
#  cloud:
#    aws:
#      credentials:
#        access-key: ${AWS_ACCESS_KEY_ID}
#        secret-key: ${AWS_SECRET_ACCESS_KEY}
#      region:
#        static: ${AWS_REGION_STATIC}
#      s3:
#        bucket: ${AWS_S3_BUCKET}
#        #enabled: false

  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash-lite
            temperature: 0.2

translation:
  deepl:
    api:
      key: ${DEEPL_API_KEY}
      base-url: ${DEEPL_API_BASE_URL}