INSERT INTO category (id, category_name) VALUES (1, 'BASKETBALL');
INSERT INTO category (id, category_name) VALUES (2, 'SOCCER');
INSERT INTO category (id, category_name) VALUES (3, 'BASEBALL');
INSERT INTO category (id, category_name) VALUES (4, 'FOOTBALL');

-- BASKETBALL Articles
INSERT INTO articles (id, category_id, title, translated_title, content, translated_content, summary, original_url, author_name, publisher_name, image_url, created_date, updated_date) VALUES
(1, 1, 'LeBron James Breaks All-Time Scoring Record', '르브론 제임스, 역대 최고 득점 기록 경신',
'The Los Angeles Lakers superstar LeBron James has officially become the NBA''s all-time leading scorer, surpassing Kareem Abdul-Jabbar''s long-standing record of 38,387 points. James achieved this historic milestone during a game against the Oklahoma City Thunder, hitting a fadeaway jump shot in the third quarter. The entire arena erupted in celebration as the game was paused to honor the moment. "This is surreal," James said after the game. "I never thought I would be in this position. I''m just grateful to be able to play the game I love."',
'로스앤젤레스 레이커스의 슈퍼스타 르브론 제임스가 공식적으로 NBA 역대 최고 득점 기록을 경신하며 카림 압둘 자바의 오랫동안 유지되던 38,387점 기록을 넘어섰다. 제임스는 오클라호마시티 썬더와의 경기에서 3쿼터 페이드어웨이 점프슛을 성공시키며 이 역사적인 이정표를 달성했다. 경기가 잠시 중단되며 순간을 기리는 동안 경기장 전체가 환호로 가득 찼다. "이건 비현실적입니다"라고 제임스는 경기 후 말했다. "제가 이 자리에 있을 거라고는 생각하지 못했습니다. 제가 사랑하는 게임을 할 수 있어서 감사합니다."',
'르브론 제임스가 NBA 역대 최고 득점 기록을 경신하며 역사를 새로 썼다.',
'https://www.espn.com/nba/story/lebron-scoring-record',
'Marc Stein',
'ESPN',
'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
DATEADD('MINUTE', -200, CURRENT_TIMESTAMP), DATEADD('MINUTE', -200, CURRENT_TIMESTAMP)),

(2, 1, 'Stephen Curry Hits 3,000 Career Three-Pointers', '스테판 커리, 통산 3000개 3점슛 달성',
'Golden State Warriors guard Stephen Curry has become the first player in NBA history to reach 3,000 career three-pointers made. Curry achieved this milestone in a victory over the Phoenix Suns, hitting his 3,000th three-pointer in the second quarter. The achievement further cements Curry''s legacy as the greatest shooter in basketball history. "Steph has revolutionized the game," Warriors coach Steve Kerr said. "His impact on how basketball is played cannot be overstated."',
'골든스테이트 워리어스의 가드 스테판 커리가 NBA 역사상 최초로 통산 3000개의 3점슛을 달성했다. 커리는 피닉스 선스와의 승리 경기에서 2쿼터에 3000번째 3점슛을 성공시키며 이 이정표를 달성했다. 이 성취는 커리를 농구 역사상 최고의 슈터로 더욱 확고히 했다. "스테프는 게임을 혁명적으로 바꿨습니다"라고 워리어스 코치 스티브 커가 말했다. "그가 농구가 어떻게 플레이되는지에 미친 영향은 과대평가할 수 없습니다."',
'스테판 커리가 NBA 역사상 최초로 통산 3000개 3점슛을 달성했다.',
'https://www.nba.com/news/curry-3000-threes',
'Tim Bontemps',
'NBA.com',
'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=800',
DATEADD('MINUTE', -190, CURRENT_TIMESTAMP), DATEADD('MINUTE', -190, CURRENT_TIMESTAMP)),

(3, 1, 'Luka Doncic Records Triple-Double in Playoff Debut', '루카 돈치치, 플레이오프 데뷔전에서 트리플 더블 기록',
'Dallas Mavericks star Luka Doncic made history in his playoff debut, recording a triple-double with 42 points, 12 rebounds, and 10 assists against the Los Angeles Clippers. The 22-year-old Slovenian became the youngest player to achieve a triple-double in a playoff debut. "Luka is special," Mavericks coach Jason Kidd said. "He has that it factor that you can''t teach. He just knows how to win."',
'댈러스 매버릭스의 스타 루카 돈치치가 플레이오프 데뷔전에서 역사를 만들며 로스앤젤레스 클리퍼스를 상대로 42점, 12리바운드, 10어시스트의 트리플 더블을 기록했다. 22세의 슬로베니아 선수는 플레이오프 데뷔전에서 트리플 더블을 달성한 최연소 선수가 되었다. "루카는 특별합니다"라고 매버릭스 코치 제이슨 키드가 말했다. "그는 가르칠 수 없는 그 무엇을 가지고 있습니다. 그는 그냥 이기는 방법을 알고 있습니다."',
'루카 돈치치가 플레이오프 데뷔전에서 트리플 더블을 기록하며 역사를 만들었다.',
'https://www.espn.com/nba/story/doncic-playoff-debut',
'Adrian Wojnarowski',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -180, CURRENT_TIMESTAMP), DATEADD('MINUTE', -180, CURRENT_TIMESTAMP)),

(4, 1, 'Giannis Antetokounmpo Wins Third MVP Award', '야니스 아데토쿤보, 3번째 MVP 수상',
'Milwaukee Bucks forward Giannis Antetokounmpo has been named the NBA Most Valuable Player for the third time in his career. The Greek Freak averaged 31.2 points, 12.8 rebounds, and 6.2 assists per game while leading the Bucks to the best record in the Eastern Conference. "This is a team award," Antetokounmpo said. "Without my teammates and coaches, none of this would be possible."',
'밀워키 벅스의 포워드 야니스 아데토쿤보가 커리어에서 세 번째로 NBA 최우수 선수로 선정되었다. 그리스 프릭은 벅스를 동부 컨퍼런스 최고 성적으로 이끌며 경기당 평균 31.2점, 12.8리바운드, 6.2어시스트를 기록했다. "이것은 팀 상입니다"라고 아데토쿤보가 말했다. "제 팀 동료들과 코치들 없이는 이것 중 아무것도 가능하지 않았을 것입니다."',
'야니스 아데토쿤보가 세 번째 MVP를 수상하며 벅스를 동부 컨퍼런스 1위로 이끌었다.',
'https://www.nba.com/news/giannis-mvp-2024',
'Shams Charania',
'The Athletic',
'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
DATEADD('MINUTE', -170, CURRENT_TIMESTAMP), DATEADD('MINUTE', -170, CURRENT_TIMESTAMP)),

(5, 1, 'Kevin Durant Returns from Injury, Scores 40 Points', '케빈 듀란트, 부상에서 복귀하며 40점 기록',
'Phoenix Suns forward Kevin Durant made a triumphant return from a knee injury, scoring 40 points in his first game back against the Denver Nuggets. Durant had been sidelined for six weeks but showed no signs of rust, shooting 15-of-22 from the field. "It feels great to be back," Durant said. "I worked hard during my recovery, and I''m ready to help this team win a championship."',
'피닉스 선스의 포워드 케빈 듀란트가 무릎 부상에서 복귀하며 덴버 너게츠와의 복귀전에서 40점을 기록했다. 듀란트는 6주간 결장했지만 녹슬 기미가 전혀 없었으며, 필드골 22개 중 15개를 성공시켰다. "돌아온 기분이 정말 좋습니다"라고 듀란트가 말했다. "회복 기간 동안 열심히 노력했고, 이 팀이 챔피언십을 따는 것을 도울 준비가 되어 있습니다."',
'케빈 듀란트가 부상에서 복귀하며 복귀전에서 40점을 기록했다.',
'https://www.espn.com/nba/story/durant-return',
'Brian Windhorst',
'ESPN',
'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=800',
DATEADD('MINUTE', -160, CURRENT_TIMESTAMP), DATEADD('MINUTE', -160, CURRENT_TIMESTAMP)),

-- SOCCER Articles
(6, 2, 'Lionel Messi Wins Eighth Ballon d''Or', '리오넬 메시, 8번째 발롱도르 수상',
'Inter Miami forward Lionel Messi has won his record-extending eighth Ballon d''Or, cementing his status as the greatest player of all time. The Argentine superstar led his country to World Cup glory and Inter Miami to their first MLS Cup title. "This is incredible," Messi said. "I never imagined I would win this award eight times. I''m grateful to everyone who supported me."',
'인터 마이애미의 포워드 리오넬 메시가 기록을 연장하는 8번째 발롱도르를 수상하며 역대 최고 선수로서의 지위를 확고히 했다. 아르헨티나 슈퍼스타는 조국을 월드컵 우승으로 이끌었고 인터 마이애미를 첫 MLS 컵 타이틀로 이끌었다. "이것은 놀랍습니다"라고 메시가 말했다. "제가 이 상을 8번 받을 거라고는 상상하지 못했습니다. 저를 지원해준 모든 분들께 감사드립니다."',
'리오넬 메시가 8번째 발롱도르를 수상하며 역대 최고 선수로서의 지위를 확고히 했다.',
'https://www.espn.com/soccer/messi-ballon-dor',
'Gabriele Marcotti',
'ESPN',
'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800',
DATEADD('MINUTE', -150, CURRENT_TIMESTAMP), DATEADD('MINUTE', -150, CURRENT_TIMESTAMP)),

(7, 2, 'Erling Haaland Breaks Premier League Goal Record', '엘링 홀란드, 프리미어리그 득점 기록 경신',
'Manchester City striker Erling Haaland has broken the Premier League single-season goal record, scoring his 35th goal of the campaign in a 3-1 victory over Arsenal. The Norwegian forward surpassed the previous record of 34 goals set by Andy Cole and Alan Shearer. "Erling is a special talent," City manager Pep Guardiola said. "He has everything a striker needs: power, speed, and incredible finishing ability."',
'맨체스터 시티의 스트라이커 엘링 홀란드가 프리미어리그 단일 시즌 득점 기록을 경신하며 아스날과의 3-1 승리에서 시즌 35호 골을 기록했다. 노르웨이 포워드는 앤디 콜과 앨런 시어러가 세운 이전 기록인 34골을 넘어섰다. "엘링은 특별한 재능입니다"라고 시티 감독 펩 과르디올라가 말했다. "그는 스트라이커가 필요한 모든 것을 가지고 있습니다: 파워, 스피드, 그리고 놀라운 마무리 능력."',
'엘링 홀란드가 프리미어리그 단일 시즌 득점 기록을 경신했다.',
'https://www.skysports.com/football/haaland-record',
'James Cooper',
'Sky Sports',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -140, CURRENT_TIMESTAMP), DATEADD('MINUTE', -140, CURRENT_TIMESTAMP)),

(8, 2, 'Real Madrid Wins Champions League Final', '레알 마드리드, 챔피언스리그 결승전 우승',
'Real Madrid has won their 15th Champions League title, defeating Manchester City 2-1 in a thrilling final at Wembley Stadium. Vinicius Junior scored the winning goal in the 89th minute, capping off a remarkable season for the Spanish giants. "This is what Real Madrid is about," manager Carlo Ancelotti said. "We never give up, and we always find a way to win."',
'레알 마드리드가 15번째 챔피언스리그 타이틀을 획득하며 웸블리 스타디움에서 열린 스릴 넘치는 결승전에서 맨체스터 시티를 2-1로 꺾었다. 비니시우스 주니어가 89분에 결승골을 넣으며 스페인 거함의 놀라운 시즌을 마무리했다. "이것이 레알 마드리드입니다"라고 감독 카를로 안첼로티가 말했다. "우리는 절대 포기하지 않으며, 항상 이기는 방법을 찾습니다."',
'레알 마드리드가 15번째 챔피언스리그 타이틀을 획득하며 역사를 만들었다.',
'https://www.espn.com/soccer/real-madrid-champions-league',
'Graham Hunter',
'ESPN',
'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800',
DATEADD('MINUTE', -130, CURRENT_TIMESTAMP), DATEADD('MINUTE', -130, CURRENT_TIMESTAMP)),

(9, 2, 'Kylian Mbappé Signs Record Contract with PSG', '킬리안 음바페, PSG와 역대 최고 계약 체결',
'Paris Saint-Germain forward Kylian Mbappé has signed a record-breaking contract extension worth €200 million over five years, making him the highest-paid player in football history. The French superstar rejected offers from Real Madrid to stay with his hometown club. "Paris is my home," Mbappé said. "I want to bring the Champions League trophy here."',
'파리 생제르맹의 포워드 킬리안 음바페가 5년간 2억 유로의 기록적인 계약 연장에 서명하며 축구 역사상 최고 연봉 선수가 되었다. 프랑스 슈퍼스타는 레알 마드리드의 제안을 거절하고 고향 클럽에 남기로 했다. "파리는 제 고향입니다"라고 음바페가 말했다. "저는 챔피언스리그 트로피를 여기로 가져오고 싶습니다."',
'킬리안 음바페가 PSG와 역대 최고 계약을 체결하며 축구 역사상 최고 연봉 선수가 되었다.',
'https://www.espn.com/soccer/mbappe-psg-contract',
'Julien Laurens',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -120, CURRENT_TIMESTAMP), DATEADD('MINUTE', -120, CURRENT_TIMESTAMP)),

(10, 2, 'Jude Bellingham Wins Golden Boy Award', '주드 벨링엄, 골든 보이 상 수상',
'Real Madrid midfielder Jude Bellingham has been named the 2024 Golden Boy, awarded to the best under-21 player in European football. The 20-year-old Englishman has been sensational in his first season with Real Madrid, scoring 18 goals from midfield. "Jude is a special player," Real Madrid manager Carlo Ancelotti said. "He has the potential to become one of the best midfielders in the world."',
'레알 마드리드의 미드필더 주드 벨링엄이 2024년 골든 보이로 선정되었으며, 이는 유럽 축구에서 최고의 21세 이하 선수에게 주어지는 상이다. 20세의 잉글랜드 선수는 레알 마드리드에서의 첫 시즌에서 감각적인 모습을 보이며 미드필더에서 18골을 기록했다. "주드는 특별한 선수입니다"라고 레알 마드리드 감독 카를로 안첼로티가 말했다. "그는 세계 최고의 미드필더 중 한 명이 될 잠재력을 가지고 있습니다."',
'주드 벨링엄이 골든 보이 상을 수상하며 유럽 최고의 젊은 선수로 인정받았다.',
'https://www.espn.com/soccer/bellingham-golden-boy',
'Mark Ogden',
'ESPN',
'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800',
DATEADD('MINUTE', -110, CURRENT_TIMESTAMP), DATEADD('MINUTE', -110, CURRENT_TIMESTAMP)),

-- BASEBALL Articles
(11, 3, 'Shohei Ohtani Achieves 60-60 Season', '오타니, 60-60 시즌 달성',
'Los Angeles Dodgers two-way star Shohei Ohtani has made baseball history by becoming the first player ever to achieve a 60-60 season, hitting 60 home runs and stealing 60 bases. The Japanese superstar accomplished this feat in a game against the San Francisco Giants, stealing his 60th base in the eighth inning. "This is incredible," Ohtani said through an interpreter. "I never thought this would be possible, but I worked hard every day to make it happen."',
'로스앤젤레스 다저스의 투웨이 스타 쇼헤이 오타니가 60홈런과 60도루를 기록하며 60-60 시즌을 달성한 최초의 선수가 되어 야구 역사를 만들었다. 일본 슈퍼스타는 샌프란시스코 자이언츠와의 경기에서 8회에 60번째 도루를 성공시키며 이 위업을 달성했다. "이것은 놀랍습니다"라고 오타니가 통역을 통해 말했다. "이것이 가능할 거라고는 생각하지 못했지만, 이를 이루기 위해 매일 열심히 노력했습니다."',
'쇼헤이 오타니가 야구 역사상 최초로 60-60 시즌을 달성했다.',
'https://www.mlb.com/news/ohtani-60-60',
'Ken Rosenthal',
'MLB.com',
'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800',
DATEADD('MINUTE', -100, CURRENT_TIMESTAMP), DATEADD('MINUTE', -100, CURRENT_TIMESTAMP)),

(12, 3, 'Aaron Judge Hits 62nd Home Run', '에런 저지, 62호 홈런 기록',
'New York Yankees outfielder Aaron Judge has hit his 62nd home run of the season, breaking Roger Maris'' American League record set in 1961. Judge accomplished this historic feat in a game against the Texas Rangers, sending a 450-foot blast into the left field stands. "This is surreal," Judge said. "To be mentioned in the same breath as Roger Maris is an honor."',
'뉴욕 양키스의 외야수 에런 저지가 시즌 62호 홈런을 기록하며 1961년에 세워진 로저 마리스의 아메리칸 리그 기록을 경신했다. 저지는 텍사스 레인저스와의 경기에서 이 역사적인 위업을 달성했으며, 450피트 홈런을 좌측 스탠드로 보냈다. "이것은 비현실적입니다"라고 저지가 말했다. "로저 마리스와 같은 맥락에서 언급되는 것은 영광입니다."',
'에런 저지가 아메리칸 리그 단일 시즌 홈런 기록을 경신했다.',
'https://www.mlb.com/news/judge-62-homers',
'Buster Olney',
'ESPN',
'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800',
DATEADD('MINUTE', -90, CURRENT_TIMESTAMP), DATEADD('MINUTE', -90, CURRENT_TIMESTAMP)),

(13, 3, 'Jacob deGrom Throws Perfect Game', '제이콥 디그롬, 완벽한 경기 달성',
'Texas Rangers pitcher Jacob deGrom has thrown a perfect game, retiring all 27 batters he faced in a 1-0 victory over the Houston Astros. The right-hander struck out 15 batters and needed just 95 pitches to complete the masterpiece. "That was the best game I''ve ever pitched," deGrom said. "Everything was working today."',
'텍사스 레인저스의 투수 제이콥 디그롬이 완벽한 경기를 던지며 휴스턴 애스트로스와의 1-0 승리에서 마주한 27명의 타자를 모두 아웃시켰다. 우완 투수는 15명의 타자를 삼진으로 잡았으며, 이 명작을 완성하는 데 단 95구만 필요했다. "그것은 제가 던진 최고의 경기였습니다"라고 디그롬이 말했다. "오늘 모든 것이 작동했습니다."',
'제이콥 디그롬이 완벽한 경기를 던지며 야구 역사에 이름을 올렸다.',
'https://www.mlb.com/news/degrom-perfect-game',
'Jeff Passan',
'ESPN',
'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800',
DATEADD('MINUTE', -80, CURRENT_TIMESTAMP), DATEADD('MINUTE', -80, CURRENT_TIMESTAMP)),

(14, 3, 'Vladimir Guerrero Jr. Wins Home Run Derby', '블라디미르 게레로 주니어, 홈런 더비 우승',
'Toronto Blue Jays first baseman Vladimir Guerrero Jr. has won the 2024 Home Run Derby, defeating Los Angeles Dodgers'' Mookie Betts in the final round. Guerrero hit 25 home runs in the final, including a 495-foot blast that shattered a scoreboard. "This is a dream come true," Guerrero said. "I grew up watching my father compete in this event, and now I''ve won it myself."',
'토론토 블루제이스의 1루수 블라디미르 게레로 주니어가 2024년 홈런 더비에서 우승하며 결승에서 로스앤젤레스 다저스의 무키 베츠를 꺾었다. 게레로는 결승에서 25개의 홈런을 기록했으며, 그 중에는 스코어보드를 부수는 495피트 홈런도 포함되어 있었다. "이것은 꿈이 현실이 된 것입니다"라고 게레로가 말했다. "저는 아버지가 이 대회에 참가하는 것을 보며 자랐고, 이제 제가 직접 우승했습니다."',
'블라디미르 게레로 주니어가 홈런 더비에서 우승하며 아버지의 뒤를 이었다.',
'https://www.mlb.com/news/guerrero-homerun-derby',
'Tim Kurkjian',
'ESPN',
'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800',
DATEADD('MINUTE', -70, CURRENT_TIMESTAMP), DATEADD('MINUTE', -70, CURRENT_TIMESTAMP)),

(15, 3, 'Fernando Tatis Jr. Returns from Suspension', '페르난도 타티스 주니어, 징계에서 복귀',
'San Diego Padres shortstop Fernando Tatis Jr. has returned from an 80-game suspension, making an immediate impact with a home run in his first at-bat. Tatis was suspended for testing positive for a performance-enhancing drug but has worked hard to regain the trust of his teammates and fans. "I made a mistake, and I''ve learned from it," Tatis said. "I''m ready to help this team win."',
'샌디에이고 파드레스의 유격수 페르난도 타티스 주니어가 80경기 징계에서 복귀하며 첫 타석에서 홈런을 기록하며 즉시 영향을 미쳤다. 타티스는 성능 향상 약물 양성 반응으로 징계를 받았지만, 팀 동료들과 팬들의 신뢰를 되찾기 위해 열심히 노력했다. "저는 실수를 했고, 그것으로부터 배웠습니다"라고 타티스가 말했다. "저는 이 팀이 이기는 것을 도울 준비가 되어 있습니다."',
'페르난도 타티스 주니어가 징계에서 복귀하며 첫 타석에서 홈런을 기록했다.',
'https://www.mlb.com/news/tatis-return',
'Jesse Rogers',
'ESPN',
'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800',
DATEADD('MINUTE', -60, CURRENT_TIMESTAMP), DATEADD('MINUTE', -60, CURRENT_TIMESTAMP)),

-- FOOTBALL Articles
(16, 4, 'Patrick Mahomes Wins Third Super Bowl MVP', '패트릭 마홈스, 3번째 슈퍼볼 MVP 수상',
'Kansas City Chiefs quarterback Patrick Mahomes has been named Super Bowl MVP for the third time, leading his team to a 31-28 overtime victory over the San Francisco 49ers. Mahomes threw for 333 yards and three touchdowns, including the game-winning score in overtime. "This team never gives up," Mahomes said. "We believe in each other, and that''s what makes us special."',
'캔자스시티 치프스의 쿼터백 패트릭 마홈스가 세 번째로 슈퍼볼 MVP로 선정되었으며, 팀을 샌프란시스코 49ers와의 연장전에서 31-28 승리로 이끌었다. 마홈스는 333야드를 던지고 3개의 터치다운을 기록했으며, 그 중에는 연장전에서 결승 득점도 포함되어 있었다. "이 팀은 절대 포기하지 않습니다"라고 마홈스가 말했다. "우리는 서로를 믿으며, 그것이 우리를 특별하게 만듭니다."',
'패트릭 마홈스가 세 번째 슈퍼볼 MVP를 수상하며 치프스를 연장전 승리로 이끌었다.',
'https://www.espn.com/nfl/mahomes-super-bowl-mvp',
'Adam Schefter',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -50, CURRENT_TIMESTAMP), DATEADD('MINUTE', -50, CURRENT_TIMESTAMP)),

(17, 4, 'C.J. Stroud Breaks Rookie Passing Record', 'C.J. 스트라우드, 신인 패싱 기록 경신',
'Houston Texans quarterback C.J. Stroud has broken the NFL rookie record for passing yards in a season, throwing for 4,557 yards and 28 touchdowns. The second overall pick has been sensational in his first year, leading the Texans to their first playoff appearance in four years. "C.J. is special," Texans coach DeMeco Ryans said. "He has all the tools to be a franchise quarterback."',
'휴스턴 텍산스의 쿼터백 C.J. 스트라우드가 NFL 신인 시즌 패싱 야드 기록을 경신하며 4,557야드와 28개의 터치다운을 기록했다. 전체 2순위 지명 선수는 첫 해에 감각적인 모습을 보이며 텍산스를 4년 만에 첫 플레이오프 진출로 이끌었다. "C.J.는 특별합니다"라고 텍산스 코치 데메코 라이언스가 말했다. "그는 프랜차이즈 쿼터백이 되기 위한 모든 도구를 가지고 있습니다."',
'C.J. 스트라우드가 NFL 신인 패싱 기록을 경신하며 텍산스를 플레이오프로 이끌었다.',
'https://www.espn.com/nfl/stroud-rookie-record',
'Dan Graziano',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -40, CURRENT_TIMESTAMP), DATEADD('MINUTE', -40, CURRENT_TIMESTAMP)),

(18, 4, 'Travis Kelce Sets Tight End Receiving Record', '트래비스 켈스, 타이트엔드 리시빙 기록 경신',
'Kansas City Chiefs tight end Travis Kelce has broken the NFL record for most receiving yards by a tight end in a single season, finishing with 1,416 yards. The 34-year-old surpassed the previous record of 1,377 yards set by George Kittle in 2018. "Travis is the best tight end in the game," Chiefs quarterback Patrick Mahomes said. "He makes my job so much easier."',
'캔자스시티 치프스의 타이트엔드 트래비스 켈스가 NFL 타이트엔드 단일 시즌 리시빙 야드 기록을 경신하며 1,416야드로 마무리했다. 34세의 선수는 2018년 조지 키틀이 세운 이전 기록인 1,377야드를 넘어섰다. "트래비스는 게임에서 최고의 타이트엔드입니다"라고 치프스 쿼터백 패트릭 마홈스가 말했다. "그는 제 일을 훨씬 쉽게 만듭니다."',
'트래비스 켈스가 타이트엔드 리시빙 기록을 경신하며 NFL 역사에 이름을 올렸다.',
'https://www.espn.com/nfl/kelce-receiving-record',
'Field Yates',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -30, CURRENT_TIMESTAMP), DATEADD('MINUTE', -30, CURRENT_TIMESTAMP)),

(19, 4, 'Myles Garrett Wins Defensive Player of the Year', '마일스 개럿, 올해의 수비 선수 수상',
'Cleveland Browns defensive end Myles Garrett has been named the NFL Defensive Player of the Year after recording 16 sacks and forcing four fumbles. The 28-year-old has been dominant all season, helping the Browns reach the playoffs for the first time in three years. "Myles is a game-changer," Browns coach Kevin Stefanski said. "He affects every play when he''s on the field."',
'클리블랜드 브라운스의 디펜시브 엔드 마일스 개럿이 16개의 색과 4개의 펌블을 강제하며 NFL 올해의 수비 선수로 선정되었다. 28세의 선수는 시즌 내내 지배적인 모습을 보이며 브라운스를 3년 만에 플레이오프에 진출시켰다. "마일스는 게임 체인저입니다"라고 브라운스 코치 케빈 스테판스키가 말했다. "그는 필드에 있을 때 모든 플레이에 영향을 미칩니다."',
'마일스 개럿이 올해의 수비 선수로 선정되며 브라운스를 플레이오프로 이끌었다.',
'https://www.espn.com/nfl/garrett-dpoy',
'Jeremy Fowler',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -20, CURRENT_TIMESTAMP), DATEADD('MINUTE', -20, CURRENT_TIMESTAMP)),

(20, 4, 'Justin Jefferson Signs Record Contract Extension', '저스틴 제퍼슨, 역대 최고 계약 연장 체결',
'Minnesota Vikings wide receiver Justin Jefferson has signed a record-breaking contract extension worth $140 million over four years, making him the highest-paid non-quarterback in NFL history. The 25-year-old has been one of the most productive receivers in the league since entering in 2020. "This is where I want to be," Jefferson said. "I love this team and this city."',
'미네소타 바이킹스의 와이드 리시버 저스틴 제퍼슨이 4년간 1억 4천만 달러의 기록적인 계약 연장에 서명하며 NFL 역사상 최고 연봉 비쿼터백 선수가 되었다. 25세의 선수는 2020년 입단 이후 리그에서 가장 생산적인 리시버 중 한 명이었다. "이것이 제가 있고 싶은 곳입니다"라고 제퍼슨이 말했다. "저는 이 팀과 이 도시를 사랑합니다."',
'저스틴 제퍼슨이 역대 최고 계약을 체결하며 NFL 역사상 최고 연봉 비쿼터백 선수가 되었다.',
'https://www.espn.com/nfl/jefferson-contract',
'Courtney Cronin',
'ESPN',
'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
DATEADD('MINUTE', -10, CURRENT_TIMESTAMP), DATEADD('MINUTE', -10, CURRENT_TIMESTAMP));
